### ISSUE TITLE
Suggestion: Add favicon notification when test passed

### ISSUE THREAD

**Issue by R1ZEN** [gemini-testing/html-reporter#247]
Favicon notification helps to understand when the test passed looking on the tab bar.

![image](https://user-images.githubusercontent.com/21066057/61717402-a7ce5780-ad69-11e9-84ec-a99af2609a01.png)

Example: http://igorprado.com/favicon-notification/

**Comment by DudaGod** [comment]
Hello.
The link - http://igorprado.com/favicon-notification/ you sent no longer responds. But anyway I understand your suggestion. Can you send PR with implementation of this feature? )

**Comment by R1ZEN** [comment]
Hi! When i try to install reporter `node_modules`, i catch the issue with module `png-img` on `nodejs 14`, also when `node_modules` are fully installed and trying to start `html-reporter`, got the error:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/pavel/Projects/opensource/html-reporter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by DudaGod** [comment]
I'm fixing it right now.

**Comment by DudaGod** [comment]
I fixed it, now it should not be reproduced.

**Comment by R1ZEN** [comment]
Good! I'll try to implement this feature and send PR

**Comment by DudaGod** [comment]
It was merged here - https://github.com/gemini-testing/html-reporter/pull/350.
