### ISSUE TITLE
hermione gui fails on windows

### ISSUE THREAD

**Issue by ghost** [gemini-testing/html-reporter#340]
I tried to launch it in git-bash and powershell. No luck. Installing `better-sqlite3` explicitly doesn't help either.

```
hermione@3.8.1
html-reporter@5.16.4
```

Config:
```
module.exports = {
    sets: {
        desktop: {
            files: [
                './features/desktop/*.spec.js',
            ],
        }
    },

    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
                version: '80.0',
            },
            gridUrl: 'http://user:user@sg.local.ru:4444/wd/hub',
        }
    },

    plugins: {
        'html-reporter/hermione': {
            enabled: false,
            path: 'reports/hermione',
            defaultView: 'all',
            baseHost: 'https://test.app.local.net/',
            scaleImages: false,
        },
    },
};
```

Stacktrace:
```
PS C:\lab\e2e2> yarn test gui
yarn run v1.22.4
$ hermione gui
Error: The specified module could not be found.
\\?\C:\lab\e2e2\node_modules\html-reporter\node_modules\better-sqlite3\build\better_sqlite3.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\lab\e2e2\node_modules\html-reporter\node_modules\better-sqlite3\lib\database.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\lab\e2e2\node_modules\html-reporter\node_modules\better-sqlite3\lib\index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\lab\e2e2\node_modules\html-reporter\lib\sqlite-adapter.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\lab\e2e2>
```

**Comment by DudaGod** [comment]
Hello.

Did you install dependencies inside html-reporter with - `yarn install`? If yes, show me a log please.

**Comment by dcbrwn** [comment]
The "missing" binary actually does exist and installed properly. `\\?\C:\lab\e2e2\node_modules\html-reporter\node_modules\better-sqlite3\build\better_sqlite3.node` is perfectly valid windows path.

Installing dependencies from root project directory as usual doesn't yield anything interesting in logs. Out of desperation I tried to run `yarn install` and `npm install` in the html-reporter directory inside node_modules. In both cases it didn't help, but both logs contained this error (seems irrelevant tbh):

```
error Package "html-reporter-test-server" refers to a non-existing file '"C:\\lab\\e2e2\\node_modules\\html-reporter\\test\\func\\plugins\\html-reporter-test-server"'.
```

**Comment by shadowusr** [comment]
We've checked how everything works on windows on modern version — now it works fine. Recently we've also fixed a few issues related to yarn, so everything should be good now. Shall any problems be encountered, a new issue may be opened.
