### ISSUE TITLE
Users/oldskytree

### ISSUE THREAD

**Issue by dicrtarasov** [gemini-testing/html-reporter#447]
Обновил версию до 9.7.0 и теперь отчет не работает:

```
1329:1 Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/oldskytree/job/search-interfaces/html-reporter/lib/static/components/controls/browser-list.js'
    at eval (1329:1:7)
    at Object.<anonymous> (report.min.js:15751:1)
    at __webpack_require__ (report.min.js:679:30)
    at fn (report.min.js:89:20)
    at eval (common-filters.js?d5f5:9:1)
    at Object.<anonymous> (report.min.js:15715:1)
    at __webpack_require__ (report.min.js:679:30)
    at fn (report.min.js:89:20)
    at eval (report-controls.js?13ce:4:1)
    at Object.<anonymous> (report.min.js:17597:1)
```

![image](https://user-images.githubusercontent.com/35159934/207468837-ed04ca04-e2c3-4e20-9301-0e4896454fca.png)

**Comment by OldSkyTree** [comment]
Проблему поправил и выкатил версию `html-reporter@9.7.1`. Спасибо за репорт!
